### PR TITLE
[1.21] Reimplement the ability to wrap ItemGroups and adjust RegistryAccess to fix #252

### LINKED ISSUE #252: (1.21) Incompatiblity with fabric api in dev enviroment under certain conditions
When loaded with fabric api if a mod registers an overly high cook time, [this code](https://github.com/FabricMC/fabric/blob/1.21/fabric-content-registries-v0/src/main/java/net/fabricmc/fabric/impl/content/registry/FuelRegistryImpl.java#L57) is ran causing `Item.toString()` to be ran, resulting into a call of `Registries.ITEM.getEntry(this).getIdAsString()` which seems to incorrectly have returned a null entry as of a result of [this mixin](https://github.com/wisp-forest/owo-lib/blob/1.21/src/main/java/io/wispforest/owo/mixin/SimpleRegistryMixin.java#L32)

[here's](https://pastebin.com/JK9qAPiC) the relevant stacktrace, and [here's](https://pastebin.com/asBst7Jc) the full `latest.log` with my mod alchemist which registers a few fuel items above what the vanilla furnace can handle, in a dev enviroment that includes both alchemist and owo-lib via modrinth maven, a standalone server seems to work.

### PR DESCRIPTION
**Pull request by Dragon-Seeker**

### CODE REVIEW

File: src/main/java/io/wispforest/owo/util/RegistryAccess.java [hunk 1]
```diff
@@ -1,56 +1,28 @@
 package io.wispforest.owo.util;
 
 import net.minecraft.registry.Registry;
-import net.minecraft.registry.RegistryKey;
 import net.minecraft.util.Identifier;
 import net.minecraft.registry.entry.RegistryEntry;
-import net.minecraft.registry.SimpleRegistry;
 import org.jetbrains.annotations.Nullable;
 
+@Deprecated
```
Comment (gliscowo) [inline src/main/java/io/wispforest/owo/util/RegistryAccess.java]: `forRemoval = true` please 😺

**Review by gliscowo — CHANGES_REQUESTED** [review]
