### PR TITLE
Fix armor trim rendering in ItemComponent (Fix #152)

### LINKED ISSUE #152: [owo-ui] armor trim is not rendered in ItemComponent
## Description

I was making a gui to edit armors and I noticed that the items do not render the trim when they are in an ItemComponent

## Attachments where the error can be seen
image
image

## Details

minecraft_version=1.20.1
fabric_version=0.84.0+1.20.1
owo_version=0.11.2-pre.9+1.20

### PR DESCRIPTION
**Pull request by Zailer43**
This happened because the armor trims are dynamically stored in the world so it requires the dynamic registry of the current world

image

### CODE REVIEW

File: src/main/java/io/wispforest/owo/ui/component/ItemComponent.java [hunk 1]
```diff
@@ -83,14 +83,16 @@ public void draw(OwoUIDrawContext context, int mouseX, int mouseY, float partial
             matrices.multiplyPositionMatrix(ITEM_SCALING);
         }
 
-        this.itemRenderer.renderItem(this.stack, ModelTransformationMode.GUI, LightmapTextureManager.MAX_LIGHT_COORDINATE, OverlayTexture.DEFAULT_UV, matrices, entityBuffers, null, 0);
+        MinecraftClient client = MinecraftClient.getInstance();
```
Comment (gliscowo) [inline src/main/java/io/wispforest/owo/ui/component/ItemComponent.java]: This should be `var` to keep consistent with the rest of the codebase

**Review by gliscowo — CHANGES_REQUESTED** [review]
Looks good overall, although I do have one nitpick about the explicit type on the new variable

**Review by gliscowo — APPROVED** [review]
